사용자 인증 관련 문제 수정(URL 접근, 로그인 페이지 강제 이동)
syg0629/wodLog pull request #21
Opened 2024-07-30 14:00 UTC by syg0629

## Issue Number
#17 

## PR Type

- [x] 버그수정
- [x] 리팩토링

## 요약
- 로그아웃 상태에서 URL로 회원 전용 페이지인 Hold 페이지에 접근 가능한 문제 수정
- 사용자 인증 확인이 완료되기 전에 로그인 페이지로 강제 이동하는 문제 수정

2024-07-31 06:47 UTC, bglgwyng requested changes

2024-07-31 06:47 UTC, bglgwyng commented on src/App.tsx
> +  const { isChecking } = useAuthSetup();
Susepnse로 해결해보세요

2024-08-03 15:05 UTC, syg0629 commented on src/App.tsx
> +  const { isChecking } = useAuthSetup();
`useAuthSetup` 훅이 불필요한 리렌더링을 유발해 삭제하였고 대신 Jotai atom을 사용하여 인증상태를 관리하도록 리팩토링하였습니다. Suspense를 사용하여 `isChecking` 관련 로직은 필요하지 않아 제거하였습니다.

2024-08-03 23:12 UTC, bglgwyng requested changes

2024-08-03 23:12 UTC, bglgwyng commented on src/App.tsx
> +  }, []);
이 변경이 잘 이해가 안됩니다

2024-08-04 00:26 UTC, syg0629 commented on src/App.tsx
> +  }, []);
`useAuthSetup` 훅에서 했던 앱 마운트 시 사용자 인증 상태를 확인하고 사용자 정보를 설정하기 위한 코드인데 해당 훅을 삭제하면서 App컴포넌트로 이동시켰습니다.

2024-08-04 02:16 UTC, bglgwyng commented on src/App.tsx
> +  }, []);
안 좋은 패턴입니다. atom의 값은 필요할때 계산되어야합니다. 지금처럼 임의로 불러오는 로직을 추가해야하면 안됩니다.

2024-08-04 05:08 UTC, syg0629 commented on src/App.tsx
> +  }, []);
회원전용 페이지 접근 제어를 위해 앱 마운트 시 바로 사용자 인증 상태 확인이 필요하다고 생각했는데, 
해당 페이지로 접근하면 `ProtectedRoute`컴포넌트의 `isAuthenticatedAtom`을 통해 이미 인증 상태를 계산하고 있었네요.. 해당 코드가 불필요하다는 것을 깨닫게 되어 제거하였습니다! 감사합니다!

2024-08-04 05:13 UTC, bglgwyng requested changes

2024-08-04 05:13 UTC, bglgwyng commented on src/App.tsx
> -
그냥 없애면 되나요? 이렇게하면 원하는데로 동작하나요? 몰라서물어봅니다.

2024-08-04 05:21 UTC, syg0629 commented on src/App.tsx
> -
넵 원하는 대로 동작합니다! https://github.com/syg0629/wodLog/pull/21#discussion_r1703048741 에서 말씀드린바와 같이 불필요한 코드였습니다.

2024-08-04 06:35 UTC, merged